### ISSUE TITLE
Change the use of the word "Delegation"

### ISSUE THREAD

**Issue by dongwon8247** [gnoswap-labs/governance#21]
It's confusing to see `Staker` and  `Delegation` (or `Delegate`).

From my understanding, `Staker` enables users to stake tokens and give voting power, a low-level requirement for governance. And `Delegation` enables users to get delegated tokens for their staking via `Staker` to give dapps/users more utilities.

We should improve the use of the word in code and improve the docs.

How about making it as "DelegatedToken"?

@notJoon @r3v4s

**Comment by notJoon** [comment]
@dongwon8247 Yeah I agree with the "delegstion" is sounds very ambiguous. I'll change the package name.

**Comment by notJoon** [comment]
Renamed `tokendelegate` to match go's naming convention.
